-- F6.1: componentes de pago CASH/CARD y resumen MIXED en tickets.
ALTER TABLE tickets DROP CONSTRAINT IF EXISTS tickets_payment_method_check;
ALTER TABLE tickets ADD CONSTRAINT tickets_payment_method_check
    CHECK (payment_method IN ('CASH', 'CARD', 'MIXED'));

CREATE UNIQUE INDEX IF NOT EXISTS uk_tickets_id_negocio ON tickets (id, negocio_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_id_negocio ON users (id, negocio_id);

CREATE TABLE payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    negocio_id bigint NOT NULL,
    ticket_id bigint NOT NULL,
    method varchar(20) NOT NULL,
    amount numeric(10,2) NOT NULL,
    cash_received numeric(10,2),
    change_given numeric(10,2),
    paid_by bigint NOT NULL,
    paid_at timestamp without time zone NOT NULL,
    legacy_imported boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uk_payments_ticket_method UNIQUE (ticket_id, method),
    CONSTRAINT fk_payments_ticket_tenant FOREIGN KEY (ticket_id, negocio_id)
        REFERENCES tickets (id, negocio_id),
    CONSTRAINT fk_payments_user_tenant FOREIGN KEY (paid_by, negocio_id)
        REFERENCES users (id, negocio_id),
    CONSTRAINT ck_payments_method CHECK (method IN ('CASH', 'CARD')),
    CONSTRAINT ck_payments_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_payments_cash_fields CHECK (
        (method = 'CARD' AND cash_received IS NULL AND change_given IS NULL)
        OR
        (method = 'CASH' AND (
            (legacy_imported AND cash_received IS NULL AND change_given IS NULL)
            OR
            (NOT legacy_imported AND cash_received IS NOT NULL AND change_given IS NOT NULL
             AND cash_received >= amount AND change_given = cash_received - amount)
        ))
    )
);

CREATE INDEX idx_payments_negocio_paid_at ON payments (negocio_id, paid_at);
CREATE INDEX idx_payments_negocio_method_paid_at ON payments (negocio_id, method, paid_at);
CREATE INDEX idx_payments_ticket_negocio ON payments (ticket_id, negocio_id);

INSERT INTO payments (
    negocio_id, ticket_id, method, amount, cash_received, change_given,
    paid_by, paid_at, legacy_imported, created_at
)
SELECT t.negocio_id, t.id, t.payment_method, t.total, NULL, NULL,
       t.paid_by, t.paid_at, true, COALESCE(t.paid_at, t.updated_at, t.created_at)
FROM tickets t
WHERE t.status = 'PAID'
  AND t.payment_method IN ('CASH', 'CARD')
  AND NOT EXISTS (
      SELECT 1 FROM payments p WHERE p.ticket_id = t.id AND p.method = t.payment_method
  );

ALTER TABLE tickets ADD CONSTRAINT ck_tickets_paid_has_payment_data CHECK (
    status <> 'PAID'
    OR (payment_method IS NOT NULL AND paid_at IS NOT NULL AND paid_by IS NOT NULL)
);
