-- F6.2: configuración de gestión de caja y catálogo tenant-scoped de cajas.
ALTER TABLE negocios
    ADD COLUMN cash_management_enabled boolean NOT NULL DEFAULT false;

CREATE TABLE cash_registers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    negocio_id bigint NOT NULL,
    name varchar(100) NOT NULL,
    normalized_name varchar(100) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    CONSTRAINT fk_cash_registers_negocio FOREIGN KEY (negocio_id) REFERENCES negocios(id),
    CONSTRAINT fk_cash_registers_created_by_tenant FOREIGN KEY (created_by, negocio_id)
        REFERENCES users(id, negocio_id),
    CONSTRAINT fk_cash_registers_updated_by_tenant FOREIGN KEY (updated_by, negocio_id)
        REFERENCES users(id, negocio_id),
    CONSTRAINT uk_cash_registers_negocio_normalized_name UNIQUE (negocio_id, normalized_name),
    CONSTRAINT ck_cash_registers_name_not_blank CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT ck_cash_registers_normalized_name_not_blank CHECK (char_length(btrim(normalized_name)) > 0)
);

CREATE INDEX idx_cash_registers_negocio_active ON cash_registers (negocio_id, active);
