-- F6.3: sesiones y apertura de caja. Sin cierre, movimientos ni relación con payments.
CREATE UNIQUE INDEX IF NOT EXISTS uk_cash_registers_id_negocio
    ON cash_registers (id, negocio_id);

CREATE TABLE cash_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    negocio_id bigint NOT NULL,
    cash_register_id bigint NOT NULL,
    status varchar(20) NOT NULL,
    opening_float numeric(10,2) NOT NULL,
    opened_by bigint NOT NULL,
    opened_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT fk_cash_sessions_negocio FOREIGN KEY (negocio_id) REFERENCES negocios(id),
    CONSTRAINT fk_cash_sessions_register_tenant FOREIGN KEY (cash_register_id, negocio_id)
        REFERENCES cash_registers(id, negocio_id),
    CONSTRAINT fk_cash_sessions_opened_by_tenant FOREIGN KEY (opened_by, negocio_id)
        REFERENCES users(id, negocio_id),
    CONSTRAINT ck_cash_sessions_status CHECK (status IN ('OPEN', 'CLOSED')),
    CONSTRAINT ck_cash_sessions_opening_float CHECK (opening_float >= 0)
);

CREATE INDEX idx_cash_sessions_negocio_status_opened
    ON cash_sessions (negocio_id, status, opened_at);
CREATE UNIQUE INDEX uk_cash_sessions_open_register
    ON cash_sessions (cash_register_id) WHERE status = 'OPEN';
CREATE UNIQUE INDEX uk_cash_sessions_open_responsible
    ON cash_sessions (negocio_id, opened_by) WHERE status = 'OPEN';
