-- F6.5: movimientos manuales append-only y cierre persistido de sesiones.
CREATE TABLE cash_movements (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 negocio_id bigint NOT NULL,
 cash_session_id bigint NOT NULL,
 type varchar(20) NOT NULL,
 amount numeric(10,2) NOT NULL,
 reason varchar(300) NOT NULL,
 performed_by bigint NOT NULL,
 performed_at timestamp without time zone NOT NULL,
 created_at timestamp without time zone NOT NULL,
 CONSTRAINT fk_cash_movements_session_tenant FOREIGN KEY (cash_session_id, negocio_id)
   REFERENCES cash_sessions(id, negocio_id),
 CONSTRAINT fk_cash_movements_actor_tenant FOREIGN KEY (performed_by, negocio_id)
   REFERENCES users(id, negocio_id),
 CONSTRAINT ck_cash_movements_type CHECK (type IN ('CASH_IN','CASH_OUT')),
 CONSTRAINT ck_cash_movements_amount CHECK (amount > 0),
 CONSTRAINT ck_cash_movements_reason CHECK (char_length(btrim(reason)) > 0)
);
CREATE INDEX idx_cash_movements_session_performed
 ON cash_movements(negocio_id, cash_session_id, performed_at, id);

ALTER TABLE cash_sessions
 ADD COLUMN closed_by bigint,
 ADD COLUMN closed_at timestamp without time zone,
 ADD COLUMN close_mode varchar(20),
 ADD COLUMN expected_cash_at_close numeric(10,2),
 ADD COLUMN counted_cash numeric(10,2),
 ADD COLUMN difference numeric(10,2),
 ADD COLUMN pending_ticket_count_at_close bigint,
 ADD COLUMN pending_ticket_amount_at_close numeric(10,2),
 ADD COLUMN pending_tickets_acknowledged boolean;

ALTER TABLE cash_sessions ADD CONSTRAINT fk_cash_sessions_closed_by_tenant
 FOREIGN KEY (closed_by, negocio_id) REFERENCES users(id, negocio_id);
ALTER TABLE cash_sessions ADD CONSTRAINT ck_cash_sessions_close_mode
 CHECK (close_mode IS NULL OR close_mode IN ('RESPONSIBLE','SUPERVISED'));
ALTER TABLE cash_sessions ADD CONSTRAINT ck_cash_sessions_close_values
 CHECK (expected_cash_at_close IS NULL OR expected_cash_at_close >= 0);
ALTER TABLE cash_sessions ADD CONSTRAINT ck_cash_sessions_counted_cash
 CHECK (counted_cash IS NULL OR counted_cash >= 0);
ALTER TABLE cash_sessions ADD CONSTRAINT ck_cash_sessions_closure_coherence CHECK (
  (status='OPEN' AND closed_by IS NULL AND closed_at IS NULL AND close_mode IS NULL
    AND expected_cash_at_close IS NULL AND counted_cash IS NULL AND difference IS NULL
    AND pending_ticket_count_at_close IS NULL AND pending_ticket_amount_at_close IS NULL
    AND pending_tickets_acknowledged IS NULL)
  OR
  (status='CLOSED' AND closed_by IS NOT NULL AND closed_at IS NOT NULL AND close_mode IS NOT NULL
    AND expected_cash_at_close IS NOT NULL AND pending_ticket_count_at_close IS NOT NULL
    AND pending_ticket_count_at_close >= 0 AND pending_ticket_amount_at_close IS NOT NULL
    AND pending_ticket_amount_at_close >= 0 AND pending_tickets_acknowledged IS NOT NULL
    AND ((reconciliation_required=true AND counted_cash IS NOT NULL AND difference IS NOT NULL)
      OR (reconciliation_required=false AND counted_cash IS NULL AND difference IS NULL)))
);
