-- F8.1: base multi-tienda. Crea Store y una tienda Principal por negocio.
-- No añade store_id a tablas operativas ni cambia el comportamiento existente.

-- Preflight ------------------------------------------------------------
DO $$
DECLARE
    users_tenant_unique boolean;
BEGIN
    IF to_regclass(current_schema() || '.negocios') IS NULL THEN
        RAISE EXCEPTION 'V8.1 abortada: no existe la tabla negocios';
    END IF;
    IF to_regclass(current_schema() || '.users') IS NULL THEN
        RAISE EXCEPTION 'V8.1 abortada: no existe la tabla users';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'negocios'
          AND column_name = 'activo' AND data_type = 'boolean'
    ) THEN
        RAISE EXCEPTION 'V8.1 abortada: negocios.activo no existe o no es boolean';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'negocios'
          AND column_name = 'cash_reconciliation_enabled' AND data_type = 'boolean'
    ) THEN
        RAISE EXCEPTION 'V8.1 abortada: negocios.cash_reconciliation_enabled no existe o no es boolean';
    END IF;
    IF EXISTS (SELECT 1 FROM negocios WHERE id IS NULL) THEN
        RAISE EXCEPTION 'V8.1 abortada: existe un negocio sin id';
    END IF;
    IF EXISTS (SELECT 1 FROM users WHERE id IS NULL OR negocio_id IS NULL) THEN
        RAISE EXCEPTION 'V8.1 abortada: existe un usuario sin id o negocio_id';
    END IF;
    IF EXISTS (
        SELECT 1 FROM users u LEFT JOIN negocios n ON n.id = u.negocio_id WHERE n.id IS NULL
    ) THEN
        RAISE EXCEPTION 'V8.1 abortada: existen usuarios asociados a un negocio inexistente';
    END IF;

    SELECT EXISTS (
        SELECT 1
        FROM pg_index i
        JOIN pg_class t ON t.oid = i.indrelid
        JOIN pg_namespace ns ON ns.oid = t.relnamespace
        WHERE ns.nspname = current_schema() AND t.relname = 'users' AND i.indisunique
          AND (
              SELECT array_agg(a.attname ORDER BY keys.ordinality)
              FROM unnest(i.indkey) WITH ORDINALITY AS keys(attnum, ordinality)
              JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = keys.attnum
          ) = ARRAY['id', 'negocio_id']::name[]
    ) INTO users_tenant_unique;

    IF NOT users_tenant_unique THEN
        RAISE EXCEPTION 'V8.1 abortada: falta un índice UNIQUE compatible en users(id, negocio_id)';
    END IF;
END $$;

-- Store ----------------------------------------------------------------
CREATE TABLE stores (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    negocio_id bigint NOT NULL,
    name varchar(100) NOT NULL,
    normalized_name varchar(100) NOT NULL,
    code varchar(50) NOT NULL,
    timezone varchar(64) NOT NULL,
    active boolean NOT NULL,
    primary_store boolean NOT NULL DEFAULT false,
    address varchar(255),
    city varchar(100),
    country_code char(2) NOT NULL,
    cash_reconciliation_enabled boolean NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    created_by bigint,
    updated_by bigint,

    CONSTRAINT pk_stores PRIMARY KEY (id),
    CONSTRAINT uk_stores_id_negocio UNIQUE (id, negocio_id),
    CONSTRAINT uk_stores_negocio_normalized_name UNIQUE (negocio_id, normalized_name),
    CONSTRAINT uk_stores_negocio_code UNIQUE (negocio_id, code),
    CONSTRAINT fk_stores_negocio FOREIGN KEY (negocio_id) REFERENCES negocios(id),
    CONSTRAINT fk_stores_created_by_tenant FOREIGN KEY (created_by, negocio_id)
        REFERENCES users(id, negocio_id),
    CONSTRAINT fk_stores_updated_by_tenant FOREIGN KEY (updated_by, negocio_id)
        REFERENCES users(id, negocio_id),
    CONSTRAINT ck_stores_name_not_blank CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT ck_stores_normalized_name_not_blank CHECK (char_length(btrim(normalized_name)) > 0),
    CONSTRAINT ck_stores_code_format CHECK (
        char_length(btrim(code)) > 0 AND code = upper(code) AND code ~ '^[A-Z0-9_-]+$'
    ),
    CONSTRAINT ck_stores_timezone_not_blank CHECK (char_length(btrim(timezone)) > 0),
    CONSTRAINT ck_stores_country_code_format CHECK (
        char_length(btrim(country_code)) = 2
        AND country_code = upper(country_code)
        AND country_code ~ '^[A-Z]{2}$'
    )
);

CREATE INDEX idx_stores_negocio_active_name
    ON stores (negocio_id, active, name, id);

CREATE UNIQUE INDEX uk_stores_one_primary_per_negocio
    ON stores (negocio_id) WHERE primary_store = true;

-- Una Principal determinista por tenant. Los actores nulos representan SYSTEM/Flyway.
INSERT INTO stores (
    negocio_id, name, normalized_name, code, timezone, active, primary_store,
    address, city, country_code, cash_reconciliation_enabled,
    created_at, updated_at, created_by, updated_by
)
SELECT
    n.id, 'Principal', 'principal', 'PRINCIPAL', 'Europe/Madrid', n.activo, true,
    NULL, NULL, 'ES', n.cash_reconciliation_enabled,
    LOCALTIMESTAMP, LOCALTIMESTAMP, NULL, NULL
FROM negocios n
WHERE NOT EXISTS (
    SELECT 1 FROM stores s WHERE s.negocio_id = n.id AND s.primary_store = true
);

-- Postflight -----------------------------------------------------------
DO $$
BEGIN
    IF (SELECT count(*) FROM stores WHERE primary_store = true)
       <> (SELECT count(*) FROM negocios) THEN
        RAISE EXCEPTION 'V8.1 postflight: el número de Stores principales no coincide con negocios';
    END IF;
    IF EXISTS (
        SELECT n.id FROM negocios n
        LEFT JOIN stores s ON s.negocio_id = n.id AND s.primary_store = true
        WHERE s.id IS NULL
    ) THEN
        RAISE EXCEPTION 'V8.1 postflight: existe un negocio sin Store Principal';
    END IF;
    IF EXISTS (
        SELECT negocio_id FROM stores WHERE primary_store = true
        GROUP BY negocio_id HAVING count(*) <> 1
    ) THEN
        RAISE EXCEPTION 'V8.1 postflight: existe un negocio con más de una Store Principal';
    END IF;
    IF EXISTS (
        SELECT 1 FROM stores
        WHERE negocio_id IS NULL OR char_length(btrim(name)) = 0
           OR char_length(btrim(normalized_name)) = 0
           OR char_length(btrim(timezone)) = 0
           OR code <> upper(code) OR code !~ '^[A-Z0-9_-]+$'
           OR char_length(btrim(country_code)) <> 2
           OR country_code <> upper(country_code) OR country_code !~ '^[A-Z]{2}$'
    ) THEN
        RAISE EXCEPTION 'V8.1 postflight: existe una Store estructuralmente inválida';
    END IF;
    IF EXISTS (
        SELECT 1 FROM stores s JOIN negocios n ON n.id = s.negocio_id
        WHERE s.primary_store = true
          AND (s.active IS DISTINCT FROM n.activo
               OR s.cash_reconciliation_enabled IS DISTINCT FROM n.cash_reconciliation_enabled)
    ) THEN
        RAISE EXCEPTION 'V8.1 postflight: Principal no refleja activo/reconciliación del negocio';
    END IF;
END $$;
