spring.application.name=api-apuntalo

spring.datasource.url=jdbc:postgresql://localhost:5432/apuntalo
spring.datasource.username=postgres
spring.datasource.password=Harbey147

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
cloudinary.cloud-name=dic0gn0is
cloudinary.api-key=472645536664777
cloudinary.api-secret=62hu7IOQ4fknAif9vVd0iA6PX9o
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:36000000}
# APP_JWT_SECRET=my-super-secret-key-my-super-secret-key-123456